// Generated by https://quicktype.io
import 'package:freezed_annotation/freezed_annotation.dart';

part 'register_dto.freezed.dart';
part 'register_dto.g.dart';

@freezed
class RegisterDto with _$RegisterDto {
  factory RegisterDto({
    required String email,
    required String firstName,
    required String lastName,
    required String password,
  }) = _RegisterDto;
  factory RegisterDto.fromJson(Map<String, dynamic> json) =>
      _$RegisterDtoFromJson(json);
}
