name: flutter_starter
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

isar_version: &isar_version ^3.1.0+1 # define the version to be used

dependencies:
  cryptography: ^2.5.0
  dartz: ^0.10.1
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.0
  flutter_hooks: null
  flutter_localizations:
    sdk: flutter
  flutter_overlay_loader: ^2.0.0
  flutter_riverpod: ^2.3.7
  flutter_secure_storage: ^8.0.0
  form_builder_validators: ^9.0.0
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  fresh_dio: ^0.4.1
  get_it: ^7.6.0
  go_router: ^10.1.0
  hooks_riverpod: ^2.3.7
  injectable: ^2.2.0
  intl: ^0.18.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.8.1
  path_provider: ^2.1.0
  permission_handler: ^11.0.0
  riverpod_annotation: ^2.1.1
  shared_preferences: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.3.0
  isar_generator: ^3.1.0+1
  json_serializable: ^6.7.1
  riverpod_generator: ^2.2.4
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
